- src/main/java/com/minecolonies/configuration/Configurations.java
- src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIStructure.java
Fixes the current gameCrash and sets the infinite resources of the builder to false in the config.
> Fixes crash + adds reminder + config change: infinite resources false

- src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java
- src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java
- src/main/java/com/minecolonies/entity/ai/citizen/fisherman/EntityAIWorkFisherman.java
- src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java
- src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java
- src/main/java/com/minecolonies/util/BlockUtils.java
- src/main/java/com/minecolonies/util/SchematicWrapper.java
Should fix the crash because of clientside only.
> Hotfix server crash

- src/main/java/com/minecolonies/colony/Colony.java
- src/main/java/com/minecolonies/colony/permissions/Permissions.java
- src/main/java/com/minecolonies/event/EventHandler.java
- src/main/java/com/minecolonies/network/messages/BlockParticleEffectMessage.java
- src/main/java/com/minecolonies/network/messages/ColonyViewBuildingViewMessage.java
- src/main/java/com/minecolonies/network/messages/ColonyViewCitizenViewMessage.java
Please test this out, I no longer received the crash after testing on my local server by myself, but I would like further testing.
> Closes #33 SMP Placement crash

- src/main/java/com/minecolonies/entity/ai/basic/AbstractAISkeleton.java
- src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java
- src/main/java/com/minecolonies/util/SchematicWrapper.java
Fixes Some bug where we don't have any issue yet
Closes #55 
- Crash when cancelling a workOrder the builder was working on.
-
-
> Should fix the workOrder problems.

- travis/build.sh
- travis/javadoc.sh
- travis/sonar.sh
Fixes the status links created by travis.
> Fix travis links

- src/main/java/com/minecolonies/colony/Colony.java
Increases y-direction search range, centers the entity, and add a small offset so they don't get stuck in the ground.
> Closes #30 Fix citizen spawns

- src/main/java/com/minecolonies/colony/Colony.java
- src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java
- src/main/java/com/minecolonies/colony/workorders/WorkOrderBuild.java
- src/main/java/com/minecolonies/entity/EntityCitizen.java
- src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java
- src/main/java/com/minecolonies/util/BlockUtils.java
- src/main/java/com/minecolonies/util/SchematicWrapper.java
- src/main/resources/META-INF/minecolonies_at.cfg
- src/main/resources/assets/minecolonies/lang/en_US.lang
Fixes #49 
Should improve getItem, this mimics getPickBlock.
Adds a different message when there is no builder.
Some general improvements to code quality.
> Improve getItem

- src/main/java/com/minecolonies/util/BlockUtils.java
Fixes #83 
Tested with and without infinite resources.
> Fix builder server crash

- src/main/java/com/minecolonies/entity/EntityCitizen.java
Fixes #90  .
- Citizens won't travel through portals anymore.
> Fix citizens travelling to nether.

- src/main/java/com/minecolonies/colony/workorders/WorkOrderBuildDecoration.java
- Fixes crash on decoration placement.
> Fixes crash on decoration placement.

- src/main/java/com/blockout/controls/ButtonImage.java
- src/main/java/com/blockout/controls/ButtonVanilla.java
- src/main/java/com/blockout/controls/ItemIcon.java
- src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java
Fix more BlockOut state issues, workaround state restore issues with ItemIcon rendering, and fix Farmer field assign button enable/disable
> More BlockOut rendering issue fixes

- src/main/java/com/blockout/Pane.java
- src/main/java/com/blockout/controls/ButtonImage.java
- src/main/java/com/blockout/controls/ButtonVanilla.java
- src/main/java/com/blockout/controls/ItemIcon.java
- src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java
- src/main/java/com/minecolonies/entity/PlayerProperties.java
- src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
- src/main/resources/assets/minecolonies/gui/windowHutFarmer.xml
Fixes rendering bug with ItemIcons
Removes notNull from players in permissions (Crashes Intellij)
Removes unnecessary view in farmerField GUI.
Also fixes problem with seed requesting.
> 1: Fixes rendering bug of itemIcon 2: NotNull crashes

- src/main/java/com/minecolonies/colony/buildings/BuildingHome.java
- src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java
- src/main/resources/assets/minecolonies/lang/en_US.lang
> Should fix achievement spam bug.

- src/main/java/com/minecolonies/colony/buildings/BuildingHome.java
- src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java
- src/main/resources/assets/minecolonies/lang/en_US.lang
> Added master fixes to develop 

- src/main/java/com/minecolonies/client/gui/WindowBuildTool.java
- src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java
- src/main/java/com/minecolonies/items/ItemBuildTool.java
- src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java
Merging the fix for 1.10 also to 1.8.9
Also fixes the inventory bugs of the buildings.
> Fixes a buildTool crash and contains DarVillous fix for rotation probs

- .pullapprove.yml
We now better represent our workflow.
Once Github releases a Pull Request Review api I will be there and integrate that :D
> Update PullApprove to version 2

- src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java
Closes #166
- fixes the lumberjack crash
> hotfix instantiate location and toplog to fix crash

- src/main/java/com/minecolonies/colony/IColony.java
- src/main/java/com/minecolonies/event/EventHandler.java
- src/main/resources/assets/minecolonies/lang/en_US.lang
Closes #163
- Adds colony info to debug screen
- fixes some sonar issues
-
> Adds colony info to the debug screen + adds some sonar fixes.

- src/main/java/com/minecolonies/entity/pathfinding/AbstractPathJob.java
- src/main/java/com/minecolonies/entity/pathfinding/PathJobFindTree.java
Closes #177
- Fixes the fence orientation problem
I elaborated this one with mainecoon.
> Fixes the Fence problems.

- src/main/java/com/minecolonies/entity/ai/minimal/EntityAIOpenFenceGate.java
- src/main/java/com/minecolonies/util/RecipeHandler.java
> Update CitizenHut Recipe

- src/main/java/com/minecolonies/MineColonies.java
- src/main/java/com/minecolonies/commands/AbstractSingleCommand.java
- src/main/java/com/minecolonies/commands/AbstractSplitCommand.java
- src/main/java/com/minecolonies/commands/ColoniesCommand.java
- src/main/java/com/minecolonies/commands/CommandEntryPoint.java
- src/main/java/com/minecolonies/commands/ListColonies.java
- src/main/java/com/minecolonies/commands/MinecoloniesCommand.java
> Should fix the exception with commands outside of the dev environment.

- src/main/java/com/minecolonies/colony/Colony.java
- src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java
- src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java
Should reduce some lag from the server.
> Should reduce some lagg

- src/main/java/com/minecolonies/colony/Colony.java
- src/main/java/com/minecolonies/network/messages/AbstractMessage.java
- src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java
- src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java
- src/main/java/com/minecolonies/network/messages/BuildRequestMessage.java
- src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java
- src/main/java/com/minecolonies/network/messages/ColonyStylesMessage.java
- src/main/java/com/minecolonies/network/messages/HireFireMessage.java
- src/main/java/com/minecolonies/network/messages/MinerSetLevelMessage.java
- src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java
- src/main/java/com/minecolonies/network/messages/PermissionsMessage.java
- src/main/java/com/minecolonies/network/messages/RecallCitizenMessage.java
- src/main/java/com/minecolonies/network/messages/ToggleJobMessage.java
- src/main/java/com/minecolonies/network/messages/TownHallRenameMessage.java
- src/main/java/com/minecolonies/network/messages/WorkOrderChangeMessage.java
Internal pr just to have sonar etc.
Fixes multithreading issues with our message handling
> Fix for messaging rework

- src/main/java/com/compatibility/Compatibility.java
- src/main/java/com/compatibility/package-info.java
- src/main/java/com/compatibility/tinkers/ToolBrokenCheck.java
- src/main/java/com/compatibility/tinkers/package-info.java
- src/main/java/com/minecolonies/util/Utils.java
Closes #219
- Add a compatibility package
- Check to see if a tinker's tool is broken before returning the mining level
> Adding some compatibility, with room for further compat in the future.

- .github/CONTRIBUTING
- src/main/java/com/compatibility/Compatibility.java
- src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
- src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java
- src/main/java/com/minecolonies/entity/ai/util/AIState.java
Closes #231 
- ~~Pam's HarvestCraft Compatibility~~ Make farmers harvest like Pam's
- Farmer optimizations
- Farmer smartifyers
> Farmer Enhancement
